
DROP TABLE SLIDESHOW;
DROP TABLE ADMINLOGIN;
DROP TABLE CART;
DROP TABLE WISHLIST;
DROP TABLE AUTH_BOOKS;
DROP TABLE AUTHOR;
DROP TABLE BOOK_CAT;
DROP TABLE CATEGORY;

DROP TABLE TRANSACTION;
DROP TABLE BILL;
DROP TABLE RATE;
DROP TABLE CATALOGUE;
DROP TABLE BOOKS;
DROP TABLE PUBLISHER;

DROP TABLE FEEDBACK;
DROP TABLE USERDETAILS;
DROP TABLE USERLOGIN;




CREATE TABLE USERLOGIN
(
USID VARCHAR(40) NOT NULL,
PWD VARCHAR(20),
PRIMARY KEY(USID)
);

CREATE TABLE USERDETAILS
(
USID VARCHAR(40) NOT NULL,
FNAME VARCHAR(20),
LNAME VARCHAR(20),
MOBILE VARCHAR(15),
EMAIL VARCHAR(40),
ADDRESS VARCHAR(50),
CITY VARCHAR(20),
STATE VARCHAR(20),
COUNTRY VARCHAR(20),
GENDER VARCHAR(10),
TYPE_OF_USER CHAR(10),
PINCODE VARCHAR(10),
DOJ DATE,
PRIMARY KEY(USID),
FOREIGN KEY (USID) REFERENCES USERLOGIN(USID) ON DELETE CASCADE
);


CREATE TABLE ADMINLOGIN
(
ADMINID VARCHAR(40) NOT NULL,
PWD VARCHAR(20) ,
PRIMARY KEY(ADMINID)
);

CREATE TABLE PUBLISHER
(
PUBID VARCHAR(40) NOT NULL,
NAME VARCHAR(20),
CITY VARCHAR(20),
PRIMARY KEY(PUBID)
);

CREATE TABLE AUTHOR
(

AUTHORID VARCHAR(40) NOT NULL,
FIRSTNAME VARCHAR(20),
LASTNAME VARCHAR(20),
PRIMARY KEY(AUTHORID)
);


CREATE TABLE BOOKS
(
ISBN VARCHAR(20) NOT NULL ,
TITLE VARCHAR(100),
NO_OF_PAGES INTEGER,
COST_PRICE FLOAT,
EDITION VARCHAR(10),
YEAR INTEGER,
PUBID VARCHAR(40) NOT NULL,
DESCRIPTION VARCHAR(50),
RATING VARCHAR(10),
IMG VARCHAR(20),
PRIMARY KEY(ISBN),
FOREIGN KEY (PUBID) REFERENCES PUBLISHER(PUBID) ON DELETE NO ACTION
);


CREATE TABLE AUTH_BOOKS
(
ISBN VARCHAR(20) NOT NULL,
AUTHID VARCHAR(20)  NOT NULL,
PRIMARY KEY(ISBN,AUTHID),
FOREIGN KEY(AUTHID) REFERENCES AUTHOR(AUTHORID) ON DELETE NO ACTION,
FOREIGN KEY(ISBN) REFERENCES BOOKS(ISBN) ON DELETE NO ACTION
);

CREATE TABLE CATEGORY
(
CAT VARCHAR(20) NOT NULL,
NAME VARCHAR(40),
PRIMARY KEY(CAT)
);

CREATE TABLE BOOK_CAT
(
ISBN VARCHAR(40) NOT NULL,
CAT VARCHAR(20) NOT NULL,
PRIMARY KEY(ISBN,CAT),
FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN) ON DELETE NO ACTION,
FOREIGN KEY (CAT) REFERENCES CATEGORY(CAT) ON DELETE NO ACTION
);

CREATE TABLE CATALOGUE
(ISBN VARCHAR(40) NOT NULL,
ACQUIRED_DATE DATE NOT NULL,
NO_COPIES INTEGER,
PRIMARY KEY(ISBN,ACQUIRED_DATE)
);


CREATE TABLE RATE
(
ISBN VARCHAR(40) NOT NULL,
SP FLOAT NOT NULL,
DISCOUNT FLOAT,
PRIMARY KEY(ISBN),
FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN) ON DELETE NO ACTION
);


CREATE TABLE BILL
(
BILLID VARCHAR(10) NOT NULL,
USID VARCHAR(40) NOT NULL,
BILL_DATE DATE,
TOTAL FLOAT,
PRIMARY KEY(BILLID),
FOREIGN KEY(USID) REFERENCES USERLOGIN(USID) ON delete NO ACTION 
);

CREATE TABLE TRANSACTION
(
BILLID VARCHAR(40) NOT NULL,
ISBN VARCHAR(40) NOT NULL,
QUANTITY INTEGER NOT NULL,
PRICE FLOAT,
DISCOUNT FLOAT,
PRIMARY KEY(BILLID,ISBN),
FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN) ON DELETE NO ACTION,
FOREIGN KEY (BILLID) REFERENCES BILL(BILLID) ON DELETE NO ACTION

);

CREATE TABLE CART
(
ISBN VARCHAR(40) NOT NULL,
QUANTITY INTEGER NOT NULL,
PRIMARY KEY(ISBN),
FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN) ON DELETE NO ACTION

);

CREATE TABLE WISHLIST
(
USID VARCHAR(40) NOT NULL,
ISBN VARCHAR(40) NOT NULL,
PRIMARY KEY(USID,ISBN),
FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN) ON DELETE NO ACTION,
FOREIGN KEY (USID) REFERENCES USERLOGIN(USID) ON DELETE NO ACTION

);
CREATE TABLE SLIDESHOW(
ID VARCHAR(10) NOT NULL,
NAME VARCHAR(30),
DES  VARCHAR(30),
PRIMARY KEY(ID)

);


CREATE TABLE FEEDBACK
(
FID VARCHAR(10) NOT NULL PRIMARY KEY,
SUBJECT VARCHAR(50),
MESSAGE VARCHAR(100) NOT NULL,
USID VARCHAR(40) NOT NULL,
FOREIGN KEY (USID) REFERENCES USERLOGIN(USID) ON DELETE CASCADE

);
